pyrad/tests/testPacket.py
This test failed in python 3.6 because after 3.5 dictionaries remember the order in which their items were added. See e.g. https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6 for more information.
The easiest fix is just to change the order that items are added in the test case, which makes tests pass again on my 3.6 CPython (and also doesn't break running this test in versions prior to 3.6).
This should close https://github.com/wichert/pyrad/issues/68 and https://github.com/wichert/pyrad/issues/70
=> Issue 68 and 70 - Update testPktEncodeAttributes to make it pass in 3.6

.gitignore
Without this, once you run tests with:
python setup.py test
the dependency directories show up in git status, which is a tad
annoying.
=> Issue63 Add *.egg directories to .gitignore.

example/auth_async.py, example/server_async.py, pyrad/client_async.py, pyrad/packet.py, pyrad/server_async.py
Added async client and server implementation for python >=3.5.
I think that we could consider to drop support of py2.7.
=> Add async Client/Server Radius

pyrad/client.py
The rtype in the docstring of `Client.CreateAuthPacket` is incorrectly given as `pyrad.packet.Packet`.
IDEs which respect the rtype of functions as declared in their docstrings (such as PyCharm) will complain about calling `AuthPacket` methods such as `PwCrypt` on the result of `Client.CreateAuthPacket` because of this rtype.
This PR updates the docstring in `Client.CreateAuthPacket` to the correct rtype (from `Packet` to `AuthPacket`) which allows these methods to be used as expected. Closes https://github.com/wichert/pyrad/issues/83.
=> Issue 83 - Correct rtype in docstring for Client.CreateAuthPacket

pyrad/tools.py
```
>>> def DecodeIPv6Prefix(addr):
...     addr = addr + b'\x00' * (18-len(addr))
...     _, length, prefix = ':'.join(map('{0:x}'.format, struct.unpack('!BB'+'H'*8, addr))).split(":", 2)
...     return str(IPNetwork("%s/%s" % (prefix, int(length, 16))))
>>> a='\x008*\x00\x0e\xe2\xf1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> import struct
>>> DecodeIPv6Prefix(a)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 3, in DecodeIPv6Prefix
ValueError: zero length field name in format
>>> addr = a + b'\x00' * (18-len(a))
>>> map('{:x}'.format, struct.unpack('!BB'+'H'*8, addr))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: zero length field name in format
>>> map('{0:x}'.format, struct.unpack('!BB'+'H'*8, …
```
=> DecodeIPv6Prefix and DecodeIPv6Addres function fix, ValueError zero length field name in format

pyrad/client.py
Fix for race condition for gigabits networks due to slow time.time()
commit binded with issue #57
=> Race condition fix due to slow time.time()

pyrad/dictionary.py, pyrad/packet.py, pyrad/tests/data/full, pyrad/tests/data/simple, pyrad/tests/testDictionary.py, pyrad/tests/testPacket.py, pyrad/tests/testTools.py, pyrad/tools.py
Supporting tlv attributes and integer64 attributes.
Tlvs are containers of other attributes, and are implemented as a map from attribute code to list of the encoded attributes.
When a TLV is encoded it is split when it is too big (larger than 255 bytes).
The encoding of a TLV encodes each instance of sub attributes together (the 1st instance of all sub attributes is sequential, the 2nd instance and so on...).
=> Added support of tlv and integer64 attributes

pyrad/client.py, pyrad/tests/mock.py, pyrad/tests/testClient.py, pyrad/tests/testProxy.py, pyrad/tests/testServer.py
We've experienced an issue when using pyrad: when using it in a long-running application keeping a large number of TCP connections open, RADIUS authentication can fail with the following exception:
ValueError: filedescriptor out of range in select()
It turns out that using select.select() is not very feasible unless you can make sure that the file descriptor of the client is less than FD_SETSIZE (practically 1024, at least on Linux).
=> Fix pyrad.Client to work with more than FD_SETSIZE file descriptors

example/coa.py, pyrad/server.py
When auth_enabled is False and acct_enabled is False, we cannot start
a listener for CoA only.
Fixes: db780ca1 ("add coa server support")
Fixes: 40c7eaba ("historics")
=> server: fix listen for CoAs without auth, neither acct , add runtime CoA+disconnect example

example/client-coa.py, example/coa.py, pyrad/server.py
We can launch multiple coa-client.py processes that listen on various UDP ports on a same local system. It is convenient to test a local CoA proxy that forwards to various CoA client.
=> coa-client: emulate fake coa-client to test CoA proxies/forwarders

pyrad/packet.py, pyrad/tests/data/chap, pyrad/tests/testPacket.py
The old code causes an error with Python 3.5.2
```
File "/path_to_module/server.py", line 269, in VerifyChapPasswd
return password == hashlib.md5("%s%s%s" % (chapid, userpwd, challenge)).digest()
TypeError: Unicode-objects must be encoded before hashing
```
=> fix VerifyChapPasswd for Python 3.5.2

pyrad/__init__.py, setup.py
Change the package version single-sourcing in order to allow getting the version with `package.__version__`, which is arguably the most common way.
Also, setting the version in `setup.py` makes it unavailable for editable installations.
=> Change version sourcing

pyrad/packet.py
Packet object is inherited from the dict class and when you try to access data by encoded int key - it works.
But if you try to access to the data by unencoded key name - it returns `None`.
```
>>reply['Callback-Number'] == reply.get('Callback-Number')  # False
>>reply[19] == reply.get(19)  # True
```
Looks like it was broken after the change of the base Packet parent `Userdict --> dict` since v1.1.
Because the original dict uses encoded keys, therefore `get()` can not find by the original
unencoded. There is much more magic with dicts since original get() will not call __getitem__().
=> Fixed packet get() method to call __getitem__ explicitly (encode)

pyrad/client.py
This PR makes it possible to change the timeout and retry parameters.
It looks like this is supposed to be allowed in the Client docstrings which are also the ones that appear in the documentation:
https://pyrad.readthedocs.io/en/latest/api/client.html#pyrad.client.Client
Should I also move the docstring from the constructor to the Client class so that the other parameters gets documented on RTD?
Fixes #118
=> Add timeout & retries as arguments to Client

pyrad/dictionary.py, pyrad/tests/data/simple, pyrad/tests/testDictionary.py
pyrad's conversion (blindly) of strings to integers is problematic.
Catch cases of hexdecimal and octal strings, since these are easy
to catch :) (and were the source of a problem for me)
=> Issue: 119 - convert string to integer in other than dec cases.

pyrad/packet.py
RADIUS servers can send not full replies, e.g `Reply-Message` could be missing in the actual reply.
We should make `def get()` to behave more similar to the python dict `def get()`, so it will not throw a KeyError if the key is missing in the reply:
```
>>>reply['Reply-Message']  # threw an error
>>>reply.get('Reply-Message')  # return None or failobj if the key is missing
```
=> Fixed packet get() method to not throw KeyError when accessing the non-existing key

pyrad/packet.py
There is a difference in getting packet text value by the text key and int key from the radius.dictionary mapping:
>>>reply['Callback-Number']
...['11FFF']
>>>reply[19]
...[b'11FFF']
Replies are not of the same type and this could lead to issues when using them for string concatenation: 'Reply: ' + reply[19] will give an error since we want to concat str and bytes.
=> Fixed getting packet value by int key.

pyrad/client_async.py, pyrad/packet.py
Authenticator attribute must be refreshed before encoding the attributes. If not, the first packet is sent with attribute 80 set to 0. Retransmits are good since the authenticator attribute is refreshed just before the packet is sent.
A second patch to fix a type error in logger in ClientAsync in case of an invalid reply.
Thank you!
=> Authenticator issue in AuthPacket

pyrad/packet.py
Several bugs, two specific to python3 and one in general.  Pre-this, hostapd can't decode Tunnel-Password. Post-this, it can. The secrets change is unnecessary, but seemed like the Right Thing to Do.
=> Fixup packet SaltCrypt

pyrad/packet.py, pyrad/tests/data/full, pyrad/tests/testPacket.py
What the title says. This is essentially the same bug as in #140 but for Message-Authenticator instead. I looked through packet.py and I _think_ this was the only other place affected by that type of bug.
=> Fix bug causing Message-Authenticator verification to fail if multiple instances of an attribute do not appear sequentially in the attributes list

pyrad/server.py
Due to commit 5b382066c49000b9336d58547af01d031ab37b73, when you pass an empty string to `BindToAddress()` it doesn't bind to socket anymore and "0.0.0.0" needs to be passed instead. The description for the function is outdated and can cause a lot of headaches.
=> Fix documentation for BindToAddress

.gitignore, pyrad/packet.py, tests/data/full, tests/testPacket.py
This PR adds the ability to salt decrypt encrypted attributes. Therefore the `pyrad.packet.Packet` class got a new function following the example of `pyrad.packet.Packet.SaltCrypt`. In addition to that the internal `_DecodeValue` function got changed and now directly decrypts the attribute whenever a user tries to access an attribute value and the attribute has `encrypt=2`.
I just stumbled over an issue working with encrypted integer attributes which is basically reproducible by following code snippet.
```python
from pyrad import dictionary, packet
attribute_dict = dictionary.Dictionary()
attribute_dict.attributes["Encrypted-Attribute"] = \
dictionary.Attribute("Encrypted-Attribute", 1, 'integer', encrypt=2)
pkg = packet.Packet(code=1, secret=b'secret', dict=attribute_dict, …
```
=> Add salt decryption of encrypted attributes

pyrad/host.py, pyrad/packet.py
There are small typos in:
- pyrad/host.py
- pyrad/packet.py
Fixes:
- Should read `interface` rather than `intereface`.
- Should read `accounting` rather than `accouting`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

pyrad/client_async.py
Some responses, such as Accounting Response, may not contain any attributes
(but only code and packet ID).
Since this is an empty dictionaty, code should be checked in this case.
Fixes #160
=> Fix ClientAsync validation of response without attributes

pyrad/server.py
When defining a client host `0.0.0.0` for a CoA radius Server, then a KeyError will occur when handling a CoA packet.
File ".../pyrad/server.py", line 250, in _HandleCoaPacket
pkt.secret = self.hosts[pkt.source[0]].secret
~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '172.16.0.100'
The reason seems to be that _AddSecret() was added at some point to support using `0.0.0.0` as a host, but the `pkt.secret = ...` assignment that it ought to replace was not removed.
This patch fixes the behavior by removing the stale assignment.
=> Fix KeyError in _HandleCoaPacket for 0.0.0.0 host

pyrad/server.py
If /etc/services is miss linux does not know what is www
=> Fix missing get addr info without services info
